command: ['python', 'app.py']
env:
  - name: 'DATABRICKS_WAREHOUSE_ID'
    valueFrom: 'sql-warehouse'
  - name: 'GENIE_SPACE_ID'
    value: '01f12b09e924156a8dd45ba78787ed15'
  - name: 'NODE_ENV'
    value: 'production'
  - name: 'LAKEBASE_INSTANCE_NAME'
    value: 'jnj-eo-analytics-demo'
  - name: 'DB_CONNECTION_STRING'
    valueFrom: 'lakebase-db'
